/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_guillaumepayet_remotenumpad_server_bluetooth_BluetoothServer */

#ifndef _Included_com_guillaumepayet_remotenumpad_server_bluetooth_BluetoothServer
#define _Included_com_guillaumepayet_remotenumpad_server_bluetooth_BluetoothServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_guillaumepayet_remotenumpad_server_bluetooth_BluetoothServer
 * Method:    addListener
 * Signature: (Lcom/guillaumepayet/remotenumpad/server/INumpadServerListener;)V
 */
JNIEXPORT void JNICALL Java_com_guillaumepayet_remotenumpad_server_bluetooth_BluetoothServer_addListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_guillaumepayet_remotenumpad_server_bluetooth_BluetoothServer
 * Method:    removeListener
 * Signature: (Lcom/guillaumepayet/remotenumpad/server/INumpadServerListener;)V
 */
JNIEXPORT void JNICALL Java_com_guillaumepayet_remotenumpad_server_bluetooth_BluetoothServer_removeListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_guillaumepayet_remotenumpad_server_bluetooth_BluetoothServer
 * Method:    open
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_guillaumepayet_remotenumpad_server_bluetooth_BluetoothServer_open
  (JNIEnv *, jobject);

/*
 * Class:     com_guillaumepayet_remotenumpad_server_bluetooth_BluetoothServer
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_guillaumepayet_remotenumpad_server_bluetooth_BluetoothServer_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
